version: '3.9'
services:
  flask_app:
    build: .
    links:
      - db
    environment:
      - FLASK_APP=app
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/flask_db
    depends_on:
      db:
        condition: service_healthy

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - flask_app

  db:
    build: ./mysql/.
    volumes:
      - mysql_volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  mysql_volumes:

